import { WWDCEvent } from "./types";

// WWDC 2025 is June 9-13. Seed events around that week.
export const SEED_EVENTS: WWDCEvent[] = [
  {
    id: "1",
    title: "WWDC Watch Party & Keynote Stream",
    description:
      "Join us at the biggest WWDC keynote watch party in SF. Giant screen, free coffee, and 200+ developers. Stick around for networking after.",
    source: "luma",
    sourceUrl: "https://lu.ma/wwdc-watch-2025",
    date: "2025-06-09",
    time: "09:30",
    endTime: "14:00",
    location: "The Midway, 900 Marin St, SF",
    neighborhood: "Dogpatch",
    host: "SF iOS Dev Community",
    tags: ["wwdc", "keynote", "networking"],
    interestLevel: "must-go",
    rsvpStatus: "confirmed",
    inviteOnly: false,
    cost: "Free",
    attendeeCount: 250,
    notes: "Big screen keynote. Get there early for good seats.",
    addedAt: "2025-05-20T10:00:00Z",
  },
  {
    id: "2",
    title: "AI x Mobile: Founders Demo Night",
    description:
      "10 startups demo AI-powered mobile apps. Judges from a16z and Sequoia. Drinks and networking after. If you're building with on-device ML, this is your crowd.",
    source: "luma",
    sourceUrl: "https://lu.ma/ai-mobile-demo",
    date: "2025-06-09",
    time: "18:00",
    endTime: "21:00",
    location: "Shack15, 1 Ferry Building, SF",
    neighborhood: "Embarcadero",
    host: "AI Tinkerers SF",
    tags: ["ai", "startup", "demo-night", "networking"],
    interestLevel: "must-go",
    rsvpStatus: "applied",
    inviteOnly: false,
    cost: "Free",
    attendeeCount: 120,
    notes: "Applied. Demo night format — great for meeting founders.",
    addedAt: "2025-05-22T14:00:00Z",
  },
  {
    id: "3",
    title: "Hacker House: Swift + AI Edition",
    description:
      "3-day hacker house in the Mission. Build something with CoreML/CreateML during WWDC week. Beds, wifi, whiteboards. Apply with your project idea.",
    source: "x",
    sourceUrl: "https://x.com/swifthackers/status/123456",
    date: "2025-06-09",
    time: "10:00",
    endTime: "23:59",
    location: "Mission District (DM for address)",
    neighborhood: "Mission",
    host: "@swifthackers",
    tags: ["hack-house", "ai", "wwdc"],
    interestLevel: "interested",
    rsvpStatus: "applied",
    inviteOnly: true,
    cost: "Free",
    attendeeCount: 20,
    notes: "DM'd. Waiting to hear back. Runs Mon-Wed.",
    addedAt: "2025-05-25T09:00:00Z",
  },
  {
    id: "4",
    title: "Anchor Brewing WWDC Meetup",
    description:
      "Casual devs-at-a-brewery meetup. No talks, just beer and conversation with fellow Apple developers. Anchor Steam on tap.",
    source: "partiful",
    sourceUrl: "https://partiful.com/e/wwdc-anchor",
    date: "2025-06-10",
    time: "17:00",
    endTime: "20:00",
    location: "Anchor Public Taps, 495 De Haro St, SF",
    neighborhood: "Potrero Hill",
    host: "Jake & Friends",
    tags: ["brewery", "meetup", "wwdc"],
    interestLevel: "must-go",
    rsvpStatus: "confirmed",
    inviteOnly: false,
    cost: "Pay for your own drinks",
    attendeeCount: 40,
    notes: "Brewery + devs = perfect combo. Confirmed going.",
    addedAt: "2025-05-28T12:00:00Z",
  },
  {
    id: "5",
    title: "Startup Pitch Night: WWDC Special",
    description:
      "5-minute pitches from early-stage startups building on Apple platforms. Feedback from YC partners. Pizza provided.",
    source: "eventbrite",
    sourceUrl: "https://eventbrite.com/e/startup-pitch-wwdc",
    date: "2025-06-10",
    time: "19:00",
    endTime: "22:00",
    location: "Galvanize, 44 Tehama St, SF",
    neighborhood: "SoMa",
    host: "YC Alumni Network",
    tags: ["startup", "demo-night", "networking"],
    interestLevel: "interested",
    rsvpStatus: "none",
    inviteOnly: false,
    cost: "Free",
    attendeeCount: 80,
    notes: "YC partner judges. Good for meeting early-stage founders.",
    addedAt: "2025-05-30T08:00:00Z",
  },
  {
    id: "6",
    title: "SwiftUI Labs: Hands-On Workshop",
    description:
      "Build a complete app with the new SwiftUI APIs announced at WWDC. Bring your laptop. Apple engineers may drop by.",
    source: "luma",
    sourceUrl: "https://lu.ma/swiftui-labs",
    date: "2025-06-11",
    time: "10:00",
    endTime: "16:00",
    location: "Apple Developer Center, One Apple Park Way",
    neighborhood: "Cupertino",
    host: "Apple Developer Relations",
    tags: ["wwdc", "workshop"],
    interestLevel: "interested",
    rsvpStatus: "waitlisted",
    inviteOnly: false,
    cost: "Free (WWDC ticket required)",
    attendeeCount: 50,
    notes: "Waitlisted. Need WWDC ticket.",
    addedAt: "2025-06-01T10:00:00Z",
  },
  {
    id: "7",
    title: "SF Founders Mixer: Post-Keynote Edition",
    description:
      "Rooftop mixer for founders and engineers. Open bar first hour. Great views of the city. Come talk about what Apple just announced.",
    source: "luma",
    sourceUrl: "https://lu.ma/sf-founders-mixer",
    date: "2025-06-09",
    time: "20:00",
    endTime: "23:00",
    location: "The View Lounge, 55 4th St, SF",
    neighborhood: "SoMa",
    host: "South Park Commons",
    tags: ["startup", "mixer", "networking"],
    interestLevel: "interested",
    rsvpStatus: "none",
    inviteOnly: false,
    cost: "Free (first hour open bar)",
    attendeeCount: 150,
    notes: "South Park Commons hosts great events. Worth going.",
    addedAt: "2025-06-02T15:00:00Z",
  },
  {
    id: "8",
    title: "WWDC Afterparty at The Minted Mule",
    description:
      "The unofficial official afterparty. DJs, cocktails, and way too many developers in one bar. Always a good time.",
    source: "partiful",
    sourceUrl: "https://partiful.com/e/wwdc-afterparty",
    date: "2025-06-11",
    time: "21:00",
    endTime: "02:00",
    location: "The Minted Mule, 351 Tehama St, SF",
    neighborhood: "SoMa",
    host: "WWDC Party Crew",
    tags: ["afterparty", "wwdc"],
    interestLevel: "maybe",
    rsvpStatus: "none",
    inviteOnly: false,
    cost: "$10 cover",
    notes: "Late night. Maybe if energy holds up by Wednesday.",
    addedAt: "2025-06-03T20:00:00Z",
  },
  {
    id: "9",
    title: "Indie Dev Breakfast Club",
    description:
      "Morning coffee and pastries with indie iOS/Mac developers. Share what you're working on. Casual and friendly.",
    source: "x",
    sourceUrl: "https://x.com/indiedevclub/status/789012",
    date: "2025-06-12",
    time: "08:00",
    endTime: "10:00",
    location: "Sightglass Coffee, 270 7th St, SF",
    neighborhood: "SoMa",
    host: "@indiedevclub",
    tags: ["meetup", "networking"],
    interestLevel: "interested",
    rsvpStatus: "none",
    inviteOnly: false,
    cost: "Buy your own coffee",
    notes: "Good for morning networking. Indie dev crowd is solid.",
    addedAt: "2025-06-04T07:00:00Z",
  },
  {
    id: "10",
    title: "Barebottle Brewing: Dev Happy Hour",
    description:
      "Weekly happy hour at Barebottle but WWDC-themed this week. They're brewing a special 'Swift Ale' for the occasion.",
    source: "manual",
    sourceUrl: "",
    date: "2025-06-12",
    time: "16:00",
    endTime: "19:00",
    location: "Barebottle Brewing, 1525 Cortland Ave, SF",
    neighborhood: "Bernal Heights",
    host: "Barebottle Brewing",
    tags: ["brewery", "meetup"],
    interestLevel: "must-go",
    rsvpStatus: "confirmed",
    inviteOnly: false,
    cost: "Pay for your own drinks",
    attendeeCount: 30,
    notes: "Barebottle is amazing. Swift Ale sounds legendary.",
    addedAt: "2025-06-04T12:00:00Z",
  },
  {
    id: "11",
    title: "Vision Pro Hack Night",
    description:
      "Build a visionOS app in one night. Vision Pro devices provided. Prizes for best spatial computing demo. Pizza and energy drinks.",
    source: "luma",
    sourceUrl: "https://lu.ma/visionpro-hack",
    date: "2025-06-10",
    time: "18:00",
    endTime: "23:59",
    location: "GitHub HQ, 88 Colin P Kelly Jr St, SF",
    neighborhood: "SoMa",
    host: "Reality Dev Guild",
    tags: ["hack-house", "wwdc", "workshop"],
    interestLevel: "interested",
    rsvpStatus: "applied",
    inviteOnly: false,
    cost: "Free",
    attendeeCount: 60,
    notes: "Vision Pro provided! Great hands-on opportunity.",
    addedAt: "2025-06-01T18:00:00Z",
  },
  {
    id: "12",
    title: "Women & Non-Binary in Swift Dinner",
    description:
      "Intimate dinner for women and non-binary Swift developers. Sponsored by Apple. Limited to 30 attendees.",
    source: "luma",
    sourceUrl: "https://lu.ma/wnb-swift",
    date: "2025-06-11",
    time: "19:00",
    endTime: "22:00",
    location: "Foreign Cinema, 2534 Mission St, SF",
    neighborhood: "Mission",
    host: "Women Who Swift",
    tags: ["networking", "wwdc"],
    interestLevel: "maybe",
    rsvpStatus: "none",
    inviteOnly: true,
    cost: "Free (sponsored)",
    attendeeCount: 30,
    notes: "",
    addedAt: "2025-06-02T10:00:00Z",
  },
  {
    id: "13",
    title: "CoreML + LLM on Device: Technical Deep Dive",
    description:
      "Technical talk on running large language models on Apple Silicon. Speakers from Apple's ML team and independent researchers. Q&A after.",
    source: "eventbrite",
    sourceUrl: "https://eventbrite.com/e/coreml-llm",
    date: "2025-06-12",
    time: "14:00",
    endTime: "17:00",
    location: "Runway, 1355 Market St #488, SF",
    neighborhood: "Mid-Market",
    host: "SF ML Meetup",
    tags: ["ai", "wwdc", "workshop"],
    interestLevel: "must-go",
    rsvpStatus: "confirmed",
    inviteOnly: false,
    cost: "Free",
    attendeeCount: 100,
    notes: "On-device LLMs are the future. Must attend.",
    addedAt: "2025-06-03T14:00:00Z",
  },
  {
    id: "14",
    title: "Closing Night: WWDC Wrap Party",
    description:
      "End-of-week celebration. Live music, open bar, photo booth. Celebrate surviving another WWDC. Dress code: your best conference tee.",
    source: "partiful",
    sourceUrl: "https://partiful.com/e/wwdc-wrap",
    date: "2025-06-13",
    time: "20:00",
    endTime: "01:00",
    location: "Public Works, 161 Erie St, SF",
    neighborhood: "Mission",
    host: "The WWDC Collective",
    tags: ["afterparty", "wwdc", "networking"],
    interestLevel: "interested",
    rsvpStatus: "none",
    inviteOnly: false,
    cost: "$15",
    notes: "Big closing party. Good way to end the week.",
    addedAt: "2025-06-05T16:00:00Z",
  },
  {
    id: "15",
    title: "Fort Point Beer x Developers Collab Tasting",
    description:
      "Fort Point is releasing a WWDC collab beer. Come taste test and hang with devs at the Ferry Building taproom.",
    source: "x",
    sourceUrl: "https://x.com/fortpointbeer/status/345678",
    date: "2025-06-13",
    time: "15:00",
    endTime: "18:00",
    location: "Fort Point Beer, Ferry Building, SF",
    neighborhood: "Embarcadero",
    host: "@fortpointbeer",
    tags: ["brewery", "meetup", "wwdc"],
    interestLevel: "must-go",
    rsvpStatus: "none",
    inviteOnly: false,
    cost: "$5 tasting flight",
    attendeeCount: 50,
    notes: "Fort Point + Ferry Building + devs. Perfect Friday.",
    addedAt: "2025-06-05T11:00:00Z",
  },
];
